---
title: "R Notebook"
output: html_notebook
---


Rscript -e "rmarkdown::render('make_consensus_matrix_for_enrichment.Rmd')"
```{r Loading packages}
library(data.table)
```


Reading IFITM3 significant correlations
```{r Reading IFITM3 significant correlations}
IFITM3_sig_cor <- fread("/sc/orga/projects/zhangb03a/lei_guo/IFITM3/Corr_Results/Genes_sig_cor_IFITM3_8_datasets.tsv")

# dropping IFITM3 V2 correlation
IFITM3_sig_cor <- IFITM3_sig_cor[!grepl("_V2_", IFITM3_sig_cor$Datasets), ]

# seperating pos/neg correlation
IFITM3_sig_cor_all <- IFITM3_sig_cor[!grepl("pos|neg", IFITM3_sig_cor$Datasets), ]

IFITM3_sig_cor_pos <- IFITM3_sig_cor[grepl("pos", IFITM3_sig_cor$Datasets), ]

IFITM3_sig_cor_neg <- IFITM3_sig_cor[grepl("neg", IFITM3_sig_cor$Datasets), ]
```


IFITM3 consensus_all matrix
```{r IFITM3 consensus matrix}
# making frequency table
IFITM3_consensus_all <- as.data.frame.matrix(table(IFITM3_sig_cor_all$Genes_cor_IFITM3, IFITM3_sig_cor_all$Datasets))

# counting significant correlations in consensus networks
IFITM3_consensus_all$rowsum <- rowSums(IFITM3_consensus_all)


# subsetting genes in each consensus network
gene_consensus_sym_all <- lapply(seq(8), function(x) rownames(subset(IFITM3_consensus_all, rowsum == x)))

gene_consensus_mod_all <- mapply(rep, paste0("Consensus_all_", seq(8)), lengths(gene_consensus_sym_all), MoreArgs = list(SIMPLIFY = F))

gene_consensus_df_all <- mapply(cbind, gene_consensus_sym_all, gene_consensus_mod_all)

gene_consensus_df_all <- lapply(gene_consensus_df_all, as.data.frame)

gene_consensus_df_all <- rbindlist(gene_consensus_df_all)

colnames(gene_consensus_df_all) <- c("Consensus_Gene", "Consensus_Network")
```


IFITM3 consensus_pos matrix
```{r IFITM3 consensus matrix pos}
# making frequency table
IFITM3_consensus_pos <- as.data.frame.matrix(table(IFITM3_sig_cor_pos$Genes_cor_IFITM3, IFITM3_sig_cor_pos$Datasets))

# counting significant correlations in consensus networks
IFITM3_consensus_pos$rowsum <- rowSums(IFITM3_consensus_pos)


# subsetting genes in each consensus network
gene_consensus_sym_pos <- lapply(seq(8), function(x) rownames(subset(IFITM3_consensus_pos, rowsum == x)))

gene_consensus_mod_pos <- mapply(rep, paste0("Consensus_pos_", seq(8)), lengths(gene_consensus_sym_pos), MoreArgs = list(SIMPLIFY = F))

gene_consensus_df_pos <- mapply(cbind, gene_consensus_sym_pos, gene_consensus_mod_pos)

gene_consensus_df_pos <- lapply(gene_consensus_df_pos, as.data.frame)

gene_consensus_df_pos <- rbindlist(gene_consensus_df_pos)

colnames(gene_consensus_df_pos) <- c("Consensus_Gene", "Consensus_Network")
```

IFITM3 consensus_neg matrix
```{r IFITM3 consensus matrix neg}
# making frequency table
IFITM3_consensus_neg <- as.data.frame.matrix(table(IFITM3_sig_cor_neg$Genes_cor_IFITM3, IFITM3_sig_cor_neg$Datasets))

# counting significant correlations in consensus networks
IFITM3_consensus_neg$rowsum <- rowSums(IFITM3_consensus_neg)


# subsetting genes in each consensus network
gene_consensus_sym_neg <- lapply(seq(8), function(x) rownames(subset(IFITM3_consensus_neg, rowsum == x)))

gene_consensus_mod_neg <- mapply(rep, paste0("Consensus_neg_", seq(8)), lengths(gene_consensus_sym_neg), MoreArgs = list(SIMPLIFY = F))

gene_consensus_df_neg <- mapply(cbind, gene_consensus_sym_neg, gene_consensus_mod_neg)

gene_consensus_df_neg <- lapply(gene_consensus_df_neg, as.data.frame)

gene_consensus_df_neg <- rbindlist(gene_consensus_df_neg)

colnames(gene_consensus_df_neg) <- c("Consensus_Gene", "Consensus_Network")
```

Combining the matricies
```{r Combining the matricies}
gene_consensus_df <- rbindlist(list(gene_consensus_df_all, gene_consensus_df_pos, gene_consensus_df_neg))
```


writing consensus df
```{r writing consensus df}
fwrite(gene_consensus_df, "/sc/orga/projects/zhangb03a/lei_guo/IFITM3/Corr_Results/Genes_sig_cor_IFITM3_consensus.tsv", sep = "\t")
```

